### PR TITLE
Add sugar for reserved words

### PR DESCRIPTION
**Pull request by benauthor**
@infecto what do you think of this approach?

### CODE REVIEW

**Comment by oliver006** [comment]
I had similar issues in melrose, this would help.
However, is it not possible to pass a param to eg. `UnicodeField()` that gives the name of the source field (and would default to the name of the attribute) ? That'd be the cleaner approach instead of relying on some `__` magic.

**Comment by benauthor** [comment]
Mmm. I don't know. How would that look

my version

``` python
def MySchema(Schema):
    thing = UnicodeField()
    __from = ObjectField()
```

your version

``` python
def MySchema(Schema):
    thing = UnicodeField()
    what_do_i_call_this = ObjectField(fieldname="from")
```

I like my version because it reads more like the shape of the blob it defines, it's less verbose, and even if it is magic syntax, it's simple magic and not confusing once you know one thing.

``` json
{
  "thing": "wow",
  "from": {
    "great": "blah"
  }
}
```

It's just a concession to the fact that not all words in python are legal, and providing a workaround without changing the philosophy of the lib. Wheras making the name configable on the field is opening up a whole rabbit hole of misdirection, user could rename every single field if they wanted, which would cause lots of noise and confusion.

**Comment by oliver006** [comment]
Eh, I get your point, it's just I'm in general a friend of making things a bit more explicit.
However, this works for me so let's go with what we got here.

**Comment by andrewkowalik** [comment]
I like this a lot. Was thinking about this last night and this is by far the most elegant solution. A little bit of magic is ok to get around these edge cases.

**Comment by andrewkowalik** [comment]
What's the review process for repos like bfh? Do we need to go through QA? 

:shipit:

**Comment by benauthor** [comment]
Nah, libs are managed by the interested parties; QA when integrated into applications. I'll merge and push to pypi after lunch.

**Pull request merged**
